services:
  db:
    image: mysql:8.0
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: shopper
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_node
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://user:password123@db:3306/shopper
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password123
      DB_NAME: shopper
      PORT: 80
    volumes:
      - .:/app
    command: ["sh", "-c", "npm install && npm run dev"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
