services:
  db:
    image: mysql:8.0
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: aquagasmeter
      MYSQL_USER: user123
      MYSQL_PASSWORD: user123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_node
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://user123:user123@db:3306/aquagasmeter
      PORT: 80
    volumes:
      - .:/app
    command: ["npm", "run", "start"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
